<?php
$g_hostname='localhost';
$g_db_type='mysqli';
$g_database_name='bugtracker';
$g_db_username='root';
$g_db_password='';
$g_signup_use_captcha=OFF;
$g_default_timezone='Europe/Berlin';
$g_crypto_master_salt='+sT3CwzT7jsC1WNkj6EtdmOO6KXqevmqMbHus+3J2HY=';
$g_phpMailer_method=PHPMAILER_METHOD_SMTP;
$g_smtp_host='localhost';